Dashboard/urls.py
from django.conf.urls import url
from . import views

app_name = 'Dashboard'


urlpatterns = [
    # /
    url(r'^$', views.a, name='a'),

    # /product/add/
    url(r'product/add/$',views.ProductCreate.as_view(), name='ProductCreate'),

    # /product/update/<pk>/
    url(r'product/update/(?P<pk>[0-9]+)/$',views.ProductUpdate.as_view(), name='ProductUpdate'),

    # /register/customer/
    url(r'^register/customer/$', views.customer_register.as_view(), name='customer_register'),

    # /register/company/
    url(r'^register/company/$', views.company_register.as_view(), name='company_register'),

    # /login/
    url(r'^login/$', views.user_login.as_view(), name='login'),

    # /logout/
    url(r'^logout/$', views.user_logout, name='logout'),
]

UnicodeTask1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Dashboard/', include('Dashboard.urls')),
]

Dashboard/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)

    def __str__(self):
        return self.user.username + '-Customer'

class Cart(models.Model):
    customer = models.OneToOneField(Customer, on_delete = models.CASCADE)
    created_at = models.DateTimeField(default=datetime.now())
    
    def __str__(self):
        return self.customer + ' - ' + str(self.created_at)

class Company(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)

    def __str__(self):
        return self.user.username + '-Company'

class Product(models.Model):
    company = models.ForeignKey(Company, on_delete = models.CASCADE)
    name = models.CharField(max_length = 50)
    desc = models.CharField(max_length = 1000)
    price = models.FloatField()
    image = models.FileField()

    def get_absolute_url(self):
        return reverse('Dashboard:a')

    def __str__(self):
        return self.name + ' - ' + str(self.price) + ' - ' + str(self.pk)

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete = models.CASCADE)
    product = models.OneToOneField(Product, on_delete = models.CASCADE)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return self.product.name + ' - ' + self.quantity

Dashboard/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class CustomerForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username']

class CompanyForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username']

Dashboard/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import Group
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from .models import *
from .forms import *

# Create your views here.

# https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html
# https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html

#####################################################

def is_customer(user):
    return user.groups.filter(name='customer').exists() or user.is_superuser

def is_company(user):
    return user.groups.filter(name='company').exists() or user.is_superuser

#####################################################

class customer_register(generic.View):
    form_class = CustomerForm
    template_name = r'Dashboard/Customer_signup.html'

    def get(self,request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form})

    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit = False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.set_password(password)
            user.save()

            customer = Customer()
            customer.user = user
            customer.save()

            group, created = Group.objects.get_or_create(name = 'customer')
            user.groups.add(group)

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('Dashboard:a')

        return render(request, self.template_name, {'form' : form})

class company_register(generic.View):
    form_class = CompanyForm
    template_name = r'Dashboard/Company_signup.html'

    def get(self,request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form})

    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit = False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.set_password(password)
            user.save()

            company = Company()
            company.user = user
            company.save()

            group, created = Group.objects.get_or_create(name = 'company')
            user.groups.add(group)

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('Dashboard:a')

        return render(request, self.template_name, {'form' : form})

class user_login(generic.View):
    form_class = AuthenticationForm
    template_name = r'Dashboard/login.html'

    def get(self,request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form})

    def post(self,request):
        form = self.form_class(data = request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('Dashboard:a')

        return render(request, self.template_name, {'form' : form})

def user_logout(request):
    logout(request)
    return redirect('Dashboard:login')
######################################################

decorators = [
    login_required,
    user_passes_test(is_company),
]

@method_decorator(decorators, name='dispatch')  
class ProductCreate(CreateView):
    model = Product
    fields = ['name','image','desc','price']

    def form_valid(self, form):
        form.instance.company = self.request.user.company
        return super(ProductCreate, self).form_valid(form)

@method_decorator(decorators, name='dispatch') 
class ProductUpdate(UpdateView):
    model = Product
    fields = ['name','image','desc','price']

    def get_queryset(self):
        base_qs = super().get_queryset()
        return base_qs.filter(company=self.request.user.company)

@method_decorator(decorators, name='dispatch')     
class ProductDelete(DeleteView):
    model = Product
    success_url = reverse_lazy('Dashboard:a')

    def get_queryset(self):
        base_qs = super().get_queryset()
        return base_qs.filter(company=self.request.user.company)

######################################################
def a(request):
    if is_customer(request.user):
        return render(request, r'Dashboard/a.html', {'type' : 'customer'})
    elif is_company(request.user):
        return render(request, r'Dashboard/a.html', {'type' : 'company'})
    else:
        return render(request, r'Dashboard/a.html', {'type' : 'None'})

Dashboard/templates/Dashboard/Company_signup.html
<head>
	<title> Register | Company </title>
</head>

<body>
	<h2> Create a New Account </h2> <br>
	<div class='panel-body'>
		<form action="" method="post" enctype = "multipart/form-data" >
			{% csrf_token %}
			{% for field in form %}
	            <span> {{ field.errors }} </span>
	            <label>{{ field.label_tag }}</label>
	            {{ field }} <br>
            {% endfor %}
			<button type='submit'>Submit!</button>
		</form>
	</div>
</body>

Dashboard/templates/Dashboard/Customer_signup.html
<head>
	<title> Register | Customer </title>
</head>

<body>
	<h2> Create a New Account </h2> <br>
	<div class='panel-body'>
		<form action="" method="post" enctype = "multipart/form-data" >
			{% csrf_token %}
			{% for field in form %}
	            <span> {{ field.errors }} </span>
	            <label>{{ field.label_tag }}</label>
	            {{ field }} <br>
            {% endfor %}
			<button type='submit'>Submit!</button>
		</form>
	</div>
</body>

Dashboard/templates/Dashboard/Product_form.html
<head>
	<title> Product </title>
</head>

<body>
	<div class='panel-body'>
		<form action="" method="post" enctype = "multipart/form-data" >
			{% csrf_token %}
			{% for field in form %}
	            <span> {{ field.errors }} </span>
	            <label>{{ field.label_tag }}</label>
	            {{ field }} <br>
            {% endfor %}
			<button type='submit'>Submit!</button>
		</form>
	</div>
</body>

Dashboard/templates/Dashboard/a.html
{{ type }}
<br>
<a href="{% url 'Dashboard:logout' %}"> Logout </a>

Dashboard/templates/Dashboard/login.html
<head>
	<title> Login </title>
</head>

<body>
	<h2> Login </h2> <br>
	<div class='panel-body'>
		<form action="" method="post" enctype = "multipart/form-data" >
			{% csrf_token %}
			{% for field in form %}
	            <span> {{ field.errors }} </span>
	            <label>{{ field.label_tag }}</label>
	            {{ field }} <br>
            {% endfor %}
			<button type='submit'>Submit!</button>
		</form>
	</div>
</body>